version: '3'
services:
  keycloak:
    image: gleroy/keycloak-bcrypt
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command: start-dev
